<?php

namespace Listerical\PackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HSCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HSCardRepository extends EntityRepository
{
}
